package project;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;

public class Welfare {
    private String discount;

    public Welfare(String discount) {
        this.discount = discount;
    }

    public String getDiscount() {
        return discount;
    }

    public void setDiscount(String discount) {
        this.discount = discount;
    }

    @Override
    public String toString() {
        return "Welfare{" +
                "discount='" + discount + '\'' +
                '}';
    }

    // the system randomly generates a four-digit number ( we don't know)
    // if there is a number that is the same as one of  the four digits generated by the system,the output is discounted by nine
    // if there is 2 numbers that are the same as two of  the four digits generated by the system,the output is discounted by eight
    // if there is 3 numbers that are the same as there of  the four digits generated by the system,the output is discounted by seven
    //if there is 4 numbers that are the same as four of  the four digits generated by the system,the output is discounted by five
    public static Welfare Lucy(int userInput) {
        Random random = new Random();
        int randomNumber = random.nextInt(9000) + 1000;
        System.out.println("The randomNumber is : " + randomNumber);
        List<Integer> randomNumberDigits = getDigits(randomNumber);
        List<Integer> userInputDigits = getDigits(userInput);
        int matchingDigits = getMatchingDigits(randomNumberDigits, userInputDigits);

        double discount = calculateDiscount(matchingDigits);
        System.out.println("The discount is : " + discount);
        return new Welfare(discount+"");
    }

    // calculate the number of matching digits between the input number and the system-generated number
    public static int getMatchingDigits(List<Integer> randomNumberDigits, List<Integer> userInputDigits) {
        int count = 0;
        for (int randomNumberDigit : randomNumberDigits) {
            if (userInputDigits.contains(randomNumberDigit)) {
                count++;
            }
        }
        return count;
    }


    public static List<Integer> getDigits(int number) {
        List<Integer> digits = new ArrayList<>();
        while (number > 0) {
            digits.add(number % 10);
            number /= 10;
        }
        return digits;
    }
    // calculate the discount rate according to the matching digits
    public static double calculateDiscount(int matchingDigits) {
        if (matchingDigits == 1) {
            return 0.9; // get 10% discount
        } else if (matchingDigits == 2) {
            return 0.8; // get 20% discount
        } else if (matchingDigits == 3) {
            return 0.7; // get 30% discount
        } else if (matchingDigits == 4) {
            return 0.5; // get 50% discount
        } else {
            return 1.0; //no digits matched,no discount
        }
    }
}

